### ISSUE TITLE
Fix Codacy integration

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#107]
I’m seeing different dashboards and grades (B versus A) when I click on the Codacy badge in the README versus clicking on the results of a scan of a PR. The URLs are completely different:

https://app.codacy.com/gh/tl-its-umich-edu/course-inventory/dashboard 
https://app.codacy.com/manual/ITS_Teaching_And_Learning/course-inventory/dashboard

I imagine there are slightly different settings in each version, resulting in the different grades? Can we consolidate and choose the best settings?

@jonespm, @lsloan, any insights here?

**Comment by lsloan** [comment]
we should be using the dashboard at (https://www.codacy.com/gh/tl-its-umich-edu/course-inventory) because that's the one associated with our GH organization, (https://github.com/tl-its-umich-edu).  Note that the other one was created with a "manual" process.

Also, I recently requested a free preview of the full Codacy service for the org. associated with that first dashboard.  @zqian recently said she would look into purchasing the full Codacy service for TL.  That purchase should be applied to that org.

**Comment by ssciolla** [comment]
K, so maybe this doesn't require a code change.

**Comment by jonespm** [comment]
Yeah, we'd have to look more at these organizations. Codacy is a little confusing. (to me)

When someone adds a project to Codacy they seem to always be associated with that project. If you turn on Codacy to comment it will comment as that user. I don't know if this has changed or not but it can be confusing.

You can move projects to an organization. I believe "tl-its-umich-edu" is one that was used to trial MWrite. Because that repo is private we have to pay for Codacy to use it. "ITS_Teaching_And_Learning" has all of our public projects.

I haven't paid much attention to the "tl-its-umich-edu".

It looks like they have new Github and Legacy organizations now. I don't know how that works. 

Codacy charges per user per month, and it's about $180/user/year so I think we'd need to think about that as we wouldn't want to include those not using it. It would save a LOT of money moving everything to Open Source. ;)

**Comment by jonespm** [comment]
It's also not entirely clear to me which Codacy "grabs" the Github project if multiple people try to add it. Really IMHO only one person should be managing Codacy at least for the initial addition of projects. I remember working through this with Zhen and getting this disconnected was a ton of steps.

**Comment by ssciolla** [comment]
Thanks for the extra information. FYI, I don't see the `course-inventory` project in the `tl-its-umich-edu` organization:

![Screen Shot 2020-04-22 at 11 53 03 AM](https://user-images.githubusercontent.com/35741256/80004233-158de800-8490-11ea-838f-43d730567e64.png)

**Comment by ssciolla** [comment]
Okay, I'm switching back to the old organization for now. More discussion about Codacy can happen elsewhere.

**Comment by ssciolla** [comment]
Just FYI, before the badge and scans were actually in sync based on recent changes, but I decided to move it all back to the legacy org (where are other open-source projects are).
