### ISSUE TITLE
Change online_meetings to write output CSV files to the root data directory

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#58]
The rest of the CSV output generated by this project writes to the `data` directory, which when using `docker-compose` is mapped to `~/data/course-inventory`. Once the job manager is finished (issue #33), we may want to use `docker-compose` to generate CSVs while continuing to develop the `online_meetings` package.

**Comment by jonespm** [comment]
Yeah we are going to need a storage volume for the Bluejeans, I figure we'll make one in general to dump the csvs. I think we can use oc rsync to semi-easily pull the data down locally without having to add anything special to the container. Though we might be able to install and use this? https://github.com/box/boxcli

**Comment by ssciolla** [comment]
That data ultimately should go to the database, so I'm not sure creating a volume is super high-priority in the OpenShift environment. Locally though, until we get the database stuff set up, you'll want to access to those files.

**Comment by ssciolla** [comment]
I guess depends on what you think the timeline is for database integration and how urgent things need to be automated.

**Comment by pushyamig** [comment]
The energy/time you put in volume container and another temp automated process you can do the DB integration.  Maybe I am missing something? Why is it taking long for BlueJeans DB integration?

**Comment by jonespm** [comment]
BlueJeans will always need a volume because the process has to download and unzip a file. #55 

It's possible that this may be able to be done in memory but that would require more code and also require that there is enough memory to manipulate the zip file.

Maybe there's something similar to this but in a package?
https://stackoverflow.com/a/10909949/3708872

**Comment by ssciolla** [comment]
We can use the `tmp` directory if we need a place to process a zip file, right? Unless the file needs to be available later.

**Comment by pushyamig** [comment]
How much data we are talking about? as it sounds to me like it huge to
unpack the file? Can we increase our container processing power? ( Not sure
how that will apply to local runs)

**Comment by jonespm** [comment]
I don't know how big the file is yet, I haven't tried. It's only in the 10s of MB's size tops though. So I *think* it would fit in memory if we wrote a process to extract it into memory. Most of the code extract to disk that I've seen. I'm hoping there'd be a package already out there that does ZipFile in memory rather than us relying on outdated Stackoverflow code.

**Comment by pushyamig** [comment]
Maybe we need to come up with smart coding that doesn't load all the files
at one time rather like stream approach.

**Comment by jonespm** [comment]
The *easiest* solution is really just to write to the a disk volume really though especially while we're still using CSV's. Maybe better ideas could come in the future. 

I think the container does also have a writable tmp partition of like 40GB that is cleared whenever the container restarts so this probably doesn't even matter that much.

**Comment by ssciolla** [comment]
This is all working now after PRs #122 and #133.
